### ISSUE TITLE
Client that waits long time gets SocketError broken pipe Or ConnectionError exception

### ISSUE THREAD

**Issue by pcwalden** [Mic92/python-mpd2#55] opened 2015-05-01 17:44 UTC
I am new to python and python-mpd2 so I may be using this package incorrectly, but I cannot determine the source of my problem. I have a python-mpd2-based client on one RaspberryPi and a standard mpd on another Pi.

My client connects to the remote mpd and then listens for IR remote commands. When the IR remote command is sent, the client formats the request and relays it to the mpd. So far I have volume up and down working nicely. The client never disconnects and supposedly keeps the connection to the mpd open all the while.

However, if I leave the client for a period of time (an hour or so), just listening for IR commands,  when I finally send a command, the client fails with a broken pipe (socket.error?) or sometimes a "ConnectionError: Connection lost while reading line". The mpd is still running and playing, although another mpd client (mpc) elsewhere has been been manipulating it.

Is it normal to expect that the original socket connection would be dropped over time or usage by a different mpd client? I have read all the documents I can find, and have failed to find any reason for the problem. I am expecting to have to catch the error and re-connect, but I'd like to know the root cause.

**Comment by Mic92** [comment] 2015-05-01 18:56
Duplicate of #31

**Closed by Mic92** 2015-05-01 18:56 UTC
Labels: duplicate

**Comment by pcwalden** [comment] 2015-05-01 20:10
Thanks!
